name: mini-nest

services:
  api:
    build:
      context: .
      target: builder
    command: npm test

  demo:
    build:
      context: .
      target: runner
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    profiles: ["demo"]
